name: Underground bug report
description: Report bug in underground modpack.
title: "[MP-UG] <title here>"
labels: ["Type: bug", "Project type: Modpack", "Project: UG"]
body:
  - type: markdown
    attributes:
      value: "Use [mclogs](https://mclo.gs/) or just type `/mclogs` in minecraft chat for publishing logs"
  - type: input
    id: mclogs
    attributes:
      label: Minecraft logs
      placeholder: https://mclo.gs/...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      value: | 
        When I ... happends. However I except ... to happen
    validations:
      required: true
  - type: checkboxes
    id: check
    attributes:
      label: Little checking
      options:
        - label: I checked [issues](https://github.com/StoryAnvil/ResourcesAndIssues/issues) for duplicates
          required: true
        - label: I didn't add any mods to original modpack
          required: false
  - type: markdown
    attributes:
      value: |
        Thanks for reporting bug!
