name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Thanks for reporting this issue. We will try to resolve it as fast as we can!"
        pr-message: "Hi! Thanks for contributing. Don't worry if your pull request will be rejected. Maybe we just in bad mood or something. If trying, you helping!"
