name: IssueCreationCheckout

on:
  issues:
    types:
      - opened

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: |
          gh issue comment $ISSUE --body "Thank you for opening this issue! We will try to resolve it ASAP"
          gh issue edit $ISSUE --add-assignee @denisJaved
